//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CD_DVD_Shop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CD_DVD_Shop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap games {
            get {
                object obj = ResourceManager.GetObject("games", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Borderlands 2 | Gearbox Software | $34.76
        ///Divinity: Original Sin 2 | Larian Studios | $22.50
        ///Final Fantasy VII | Square Enix | $45.12
        ///The Legend of Zelda: Breath of the Wild | Nintendo | $29.88
        ///Super Mario Odyssey | Nintendo | $19.99
        ///Red Dead Redemption 2 | Rockstar Games | $39.25
        ///The Witcher 3: Wild Hunt | CD Projekt | $28.73
        ///Dark Souls | FromSoftware | $17.64
        ///Minecraft | Mojang Studios | $12.99
        ///Overwatch | Blizzard Entertainment | $24.37
        ///Fortnite | Epic Games | $14.92
        ///Call of Duty: Modern Warfa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string games1 {
            get {
                return ResourceManager.GetString("games1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap movies {
            get {
                object obj = ResourceManager.GetObject("movies", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furiosa: A Mad Max Saga | George Miller | $6.72
        ///Atlas | Chad Stahelski, David Leitch | $3.14
        ///Civil War | Anthony Russo, Joe Russo | $8.27
        ///The Fall Guy | Dwayne Johnson, Dany Garcia | $5.48
        ///Mad Max: Fury Road | George Miller | $9.01
        ///Kingdom of the Planet of the Apes | Peter Chernin, Dylan Clark | $7.83
        ///Dune: Part Two | Denis Villeneuve, Mary Parent | $4.36
        ///IF | Jason Blum | $2.75
        ///Challengers | Ridley Scott, Kevin J. Walsh | $1.92
        ///The First Omen | David S. Goyer, Kevin Turen | $6.19
        ///The Garfield Mov [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string movies1 {
            get {
                return ResourceManager.GetString("movies1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap music {
            get {
                object obj = ResourceManager.GetObject("music", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L’amour vivant | The Sami Yusuf ensemble | $34.76
        ///Raat ki rani | Arooj Aftab | $22.50
        ///Lunch | Billie Eilish | $45.12
        ///Jako | Ladaniva | $29.88
        ///January 13 for Soyberk | Anıl Şallıel | $19.99
        ///Starburster | Fontaines D.C. | $39.25
        ///Prologue | Kamasi Washington | $28.73
        ///The code | Nemo | $17.64
        ///odd | Haya band (乐团) | $12.99
        ///Tera jugg | Kiran Ahluwalia | $24.37
        ///euphoria | Kendrick Lamar | $14.92
        ///Gentle heart, healing hand | Fia | $47.81
        ///Dreamfear / Boy sent from above | Burial | $31.05
        ///Illusion | Dua  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string music1 {
            get {
                return ResourceManager.GetString("music1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thumb_1920_178525_3546664363 {
            get {
                object obj = ResourceManager.GetObject("thumb-1920-178525-3546664363", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
